# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=566)),
                ('phone', models.CharField(max_length=56)),
                ('address', models.CharField(max_length=56)),
                ('logo', models.ImageField(upload_to='restaurant_logo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=566)),
                ('firstname', models.CharField(max_length=566)),
                ('lastname', models.CharField(max_length=566)),
                ('password', models.CharField(max_length=566)),
                ('email', models.CharField(max_length=566)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='foodieapp.User'),
        ),
    ]
